### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by azoff** [fwestenberg/devialet#5]
No issue, just wanted to say thanks for figuring this out. I started to probe the HTTP interface to try and reverse engineer this. I had a hunch to search github, and you are literally the only person to have ever figured out their interface (would love to know how you were able to figure it out btw... intercepting traffic from the app?). Anyhow, you saved me a lot of time and now my lazy ass can switch to phono without getting out of my chair to grab my phone. Appreciate that :)

**Comment by fwestenberg** [comment]
Thanks for your message. Happy you enjoy it as much as I do!
Just a few updates ago, Devialet released the official API, complete with documentation. You can find it here: https://help.devialet.com/hc/en-us/articles/4415207423378-Phantom-s-documentation-for-piloting-them-via-IP

Do you use the Home Assistant integration as well? If so, it would probably help if you can review it here:
https://github.com/home-assistant/core/pull/86551
