### ISSUE TITLE
Update fails

### ISSUE THREAD

**Issue by gstax** [fwestenberg/devialet#7]
Hi,

HA says that there's an update from 1.4.2 -> 1.4.3, but the update fails (in a loop it seems).

It seems that the repo changed location but the link in the README gives 404.

Reading the commits, it seems that current version is 1.4.5.

How can I get it?

Thanks, the integration is really usefull.

**Comment by fwestenberg** [comment]
You're probably still using the HACS version, while the official version is already released. 
Please navigate to HACS, remove the Devialet integration there.

**Comment by gstax** [comment]
Yes I'm still using the HACS version, didn't know a official version came out.
Will do as you say.

Thanks for the quick answer!
