### ISSUE TITLE
TTS possible?

### ISSUE THREAD

**Issue by kersten-lohmeyer** [fwestenberg/devialet#8]
Hi, I was just wondering if TTS is possible on these speakers using Home Assistant?

Thanks

P.S.: No issue, but didn't find another way of contacting you.

**Comment by fwestenberg** [comment]
Hello Kersten, 

It should probably be possible. The speakers do support UPnP and streaming over websocket. But unfortunately I don't have the time to look into it.

**Comment by kersten-lohmeyer** [comment]
Ok, thank you!

**Comment by fwestenberg** [comment]
@kersten-lohmeyer you might want to follow this [PR](https://github.com/home-assistant/core/pull/134168) :wink:
